Restaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace Restaurants.Models 
{
  public class Cuisine
  {
    public int CuisineId {get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public List<Restaurant> Restaurants { get; set; }
  }
}

Restaurants/Models/Restaurant.cs
namespace Restaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public int Rating { get; set; }
    public string Address { get; set; }
    public int CuisineId { get; set; }
    public Cuisine Cuisine { get; set; }
  }
}

Restaurants/Models/RestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurants.Models
{
  public class RestaurantsContext : DbContext
  {
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Cuisine> Cuisines { get; set; }

    public RestaurantsContext(DbContextOptions options) : base(options) { }
  }
}

Restaurants/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace Restaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly RestaurantsContext _db;

    public CuisinesController(RestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.Include(cuisine => cuisine.Restaurants).FirstOrDefault(cuisine => cuisine.CuisineId == id);

      return View(thisCuisine);
    }
    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(this);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Cuisines.Update(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }  
}

Restaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurants.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Restaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace Restaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly RestaurantsContext _db;

    public RestaurantsController(RestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants
                                  .Include(restaurant => restaurant.Cuisine)
                                  .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
                                      .Include(restaurant => restaurant.Cuisine)
                                      .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Restaurants.Update(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Restaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Cuisine;

<h2>Add a Cuisine Type<h2>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  <input type="submit" value="Add new cuisine"/>
}

<p>@Html.ActionLink("Show all cuisine", "Index");

Restaurants/Views/Cuisines/Delete.cshtml
@{
  Layout="_Layout";
}

@model Restaurants.Models.Cuisine

<h2>Do you really want to delete this...?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to list", "Index")

Restaurants/Views/Cuisines/Details.cshtml
@{
  Layout="_Layout";
}

@model Restaurants.Models.Cuisine
@using Restaurants.Models

<h2>Cuisine Information<h2>
<hr>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
@if (@Model.Restaurants.Count == 0)
{
  <h3>No Restaurants information has been added to this yet!</h3>
}
else
{
  <h3>Restaurants:</h3>
  <ul>
    @foreach (Restaurant restaurant in Model.Restaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit cuisines", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete cuisines", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Restaurants/Views/Cuisines/Edit.cshtml
@{
  Layout="_Layout";
}

@model Restaurants.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Restaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurants.Models;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No types of cuisines has been entered yet!</h3>
}

<ul>
  @foreach(Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Add new restaurant", "Create", "Restaurants")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Restaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Find a Restaurant</h1>
<p>@Html.ActionLink("List of Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>

Restaurants/Views/Restaurant/Details.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Restaurant Details<h2>
<h3>@Html.DisplayNameFor(model => model.Name): @HtmlDisplayFor(model => model.Name)</h3>

Restaurants/Views/Restaurant/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurants.Models;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
}
else
{
  <ul>
    @foreach (Restaurant restaurant in Model)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })  </li>
    }
  </ul>
}

Restaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>ADD A NEW RESTAURANT</h2>

<p><strong>Note!</strong>You need to add at least 1 type of cuisine before you add a restaurant.</p>
<p>Go to @Html.ActionLink("this page", "Create", "Cuisines") to add a cuisine.</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Rating)
  @Html.TextBoxFor(model => model.Rating)
  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)
  
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")
  
  <input type='submit' value="Add new restuarant" class="btn btn-default"/>
}

<p>@Html.ActionLink("Show all restaurants", "Index")</p>

Restaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Delete a restaurant</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}
@Html.ActionLink("Back to list", "Index")

Restaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Restaurant Details<h2>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h4>@Html.DisplayNameFor(model => model.Rating): @Html.DisplayFor(model => model.Rating)</h4>
<h4>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)</h4>

<h3>@Html.DisplayNameFor(model => model.Cuisine): @Html.DisplayFor(model => model.Cuisine.Name)</h3>

<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Restaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Rating)
  @Html.EditorFor(model => model.Rating)
  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Restaurants", "Index")</p>

Restaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @using Restaurants.Models;

  <h1>Restaurants</h1>

  @if (@Model.Count == 0)
  {
    <h3>No items have been added yet!</h3>
  }

  <ul>
    @foreach (Restaurant restaurant in Model)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
    }
  </ul>

  <p>@Html.ActionLink("Add a restaurant", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Restaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants!</title>
    <link 
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
    <style>
body {
  background-color: #E6E6FA;
}
</style>
  </head>
  <body>
    
    @RenderBody()
  </body>
</html>